In [5]:
import numpy as np

def calc_multinomial_loglikelihood(n, p):

    ll = np.sum([i * np.log(j) for i,j in zip(n, p)])

    return ll

n = [2500, 2500, 2500, 2500, 2500]
p = [0.8, 0.05, 0.05, 0.05, 0.05]

calc_multinomial_loglikelihood(n, p)

-30515.181613825436

In [112]:
arr_clipa = 0
arr_clipb = 120
sd = 1000
vloc = 40

scipy.stats.truncnorm.rvs((arr_clipa - vloc)/sd, (arr_clipb - vloc)/sd, loc = 40, scale = sd, size = 100)

array([111.13893724,  35.89918243, 115.81964782,  20.8859525 ,
        28.31727721,  94.57664582,  39.66243067,  13.41020977,
        39.01117702,  92.13388814,  41.80358177,  33.39092297,
        59.99475713,  94.85129076,  63.6414993 ,  95.58777283,
        32.00342784,  98.78513489,  56.08158286, 109.24966333,
        24.1177839 ,   1.3835081 ,  23.24742918,  53.21201742,
       119.63922036, 108.72019315, 111.42170692,  24.65257178,
        94.95741322,  32.78101791, 104.09199581,  31.73486585,
        22.81574144,  45.7727699 ,  56.44219393,  91.60181372,
        89.77552699,  31.16994997,  28.47475784, 107.198945  ,
       107.70795401, 103.10639574,  45.01377463,  70.28065556,
        69.7039475 ,  13.40963872,  23.27969881,  20.59324097,
        86.5933693 ,  73.4080294 ,  91.30896835,  27.89725964,
        24.99636158,  19.18354709, 108.8367    ,  10.26709417,
        10.38388404,  27.27752812,  11.97114006, 106.86198142,
        91.82181905,  73.18991126,  65.04151717,  47.08

In [113]:
import numpy as np

In [118]:
size, array_length = 100, 120
Varray, Aarray = np.zeros((size, array_length)), np.zeros((size, array_length))
Varray

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [176]:
vloc, aloc = 20, 20
array_length = 120
vvar = 1
avar = 1

from scipy.stats import truncnorm

lowerbound, upperbound = ((0 - vloc) / vvar), ((array_length - vloc) / vvar)

# Sample from these stimulus distributions
Vsamples, Asamples = np.round(truncnorm.rvs(lowerbound, upperbound, loc = vloc, scale = vvar, size = size)), np.round(truncnorm.rvs(lowerbound, upperbound, loc = aloc, scale = avar, size = size))
Vsamples, Asamples = Vsamples.astype("int32"), Asamples.astype("int32")

In [165]:
Vsamples.dtype

dtype('float64')

In [180]:
plusminusspread = 1
stimarray = np.zeros((size, 2, array_length))

for i,j,c, in zip(Vsamples, Asamples, range(0, size)):

        vspread, aspread = [(i-plusminusspread), i, (i+plusminusspread)], [(j-plusminusspread), j, (j+plusminusspread)] # So get a list of where to begin and end adding zeros

        for p,q in zip(vspread, aspread):

            print(type(i), type(j), type(c), type(p), type(q))

            print(c, 0, p)
            stimarray[c, 0 ,p], stimarray[c, 1, q] = 1, 1

<class 'numpy.int32'> <class 'numpy.int32'> <class 'int'> <class 'numpy.int64'> <class 'numpy.int64'>
0 0 20
<class 'numpy.int32'> <class 'numpy.int32'> <class 'int'> <class 'numpy.int32'> <class 'numpy.int32'>
0 0 21
<class 'numpy.int32'> <class 'numpy.int32'> <class 'int'> <class 'numpy.int64'> <class 'numpy.int64'>
0 0 22
<class 'numpy.int32'> <class 'numpy.int32'> <class 'int'> <class 'numpy.int64'> <class 'numpy.int64'>
1 0 19
<class 'numpy.int32'> <class 'numpy.int32'> <class 'int'> <class 'numpy.int32'> <class 'numpy.int32'>
1 0 20
<class 'numpy.int32'> <class 'numpy.int32'> <class 'int'> <class 'numpy.int64'> <class 'numpy.int64'>
1 0 21
<class 'numpy.int32'> <class 'numpy.int32'> <class 'int'> <class 'numpy.int64'> <class 'numpy.int64'>
2 0 20
<class 'numpy.int32'> <class 'numpy.int32'> <class 'int'> <class 'numpy.int32'> <class 'numpy.int32'>
2 0 21
<class 'numpy.int32'> <class 'numpy.int32'> <class 'int'> <class 'numpy.int64'> <class 'numpy.int64'>
2 0 22
<class 'numpy.int32

In [182]:
stimarray[20]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.,

In [222]:
from itertools import product

class stimGenerator:

    """
        Class to create artificial datasets mimicking stimulus statistics
        in conventional multisensory integration paradigms, which can be
        tested on neural networks.

        Args:

        array_length -> int(); length of the proposed 1 * n array.

        spread -> int(); determines how many entries around the "stimulus
                    landing spot" that is changed, i.e. size of the
                    stimulus in the array. 

        n_locations -> int(); determines the amount of equally spaced
                       locations at which stimuli may appear. 

        variance_conditions -> list; determines n of variance conditions
                                for which stimuli are generated.
    """

    def __init__(self, array_length, spread, n_locations, variance_conditions):

                self.array_length = array_length
                self.spread = spread
                self.n_locations = n_locations
                self.variance_conditions = variance_conditions
                print("Loaded stimulus generator.")
    
    def generate(self, size):
        
        """Generates dataset of arrays of where n = size
        size -> int(); size of the dataset. 
        """

        # Create data structure to hold the dataset
        dataset = {i:None for i in self.variance_conditions} # use dict to enable types of trials to remain marked?
        n_percond = ((size / len(self.variance_conditions)) / self.n_locations) # find n to generate per cond
        
        # Find locations at which stimuli can be placed
        bin_center = self.array_length / self.n_locations
        loc_list = [i*bin_center+bin_center for i in range(self.n_locations)]
        Vlist, Alist = loc_list, loc_list

        combinations = list(product(Vlist, Alist, self.variance_conditions))


        #### Create variable to be uesd to create the bin_center

        # Generate trials and add to dict!

        return dataset

In [223]:
gen = stimGenerator(120, 1, 5, [1,2,3])
gen.generate(size = 100)

Loaded stimulus generator.
[(24.0, 24.0, 1), (24.0, 24.0, 2), (24.0, 24.0, 3), (24.0, 48.0, 1), (24.0, 48.0, 2), (24.0, 48.0, 3), (24.0, 72.0, 1), (24.0, 72.0, 2), (24.0, 72.0, 3), (24.0, 96.0, 1), (24.0, 96.0, 2), (24.0, 96.0, 3), (24.0, 120.0, 1), (24.0, 120.0, 2), (24.0, 120.0, 3), (48.0, 24.0, 1), (48.0, 24.0, 2), (48.0, 24.0, 3), (48.0, 48.0, 1), (48.0, 48.0, 2), (48.0, 48.0, 3), (48.0, 72.0, 1), (48.0, 72.0, 2), (48.0, 72.0, 3), (48.0, 96.0, 1), (48.0, 96.0, 2), (48.0, 96.0, 3), (48.0, 120.0, 1), (48.0, 120.0, 2), (48.0, 120.0, 3), (72.0, 24.0, 1), (72.0, 24.0, 2), (72.0, 24.0, 3), (72.0, 48.0, 1), (72.0, 48.0, 2), (72.0, 48.0, 3), (72.0, 72.0, 1), (72.0, 72.0, 2), (72.0, 72.0, 3), (72.0, 96.0, 1), (72.0, 96.0, 2), (72.0, 96.0, 3), (72.0, 120.0, 1), (72.0, 120.0, 2), (72.0, 120.0, 3), (96.0, 24.0, 1), (96.0, 24.0, 2), (96.0, 24.0, 3), (96.0, 48.0, 1), (96.0, 48.0, 2), (96.0, 48.0, 3), (96.0, 72.0, 1), (96.0, 72.0, 2), (96.0, 72.0, 3), (96.0, 96.0, 1), (96.0, 96.0, 2), (96.0, 96.0

{1: None, 2: None, 3: None}