In [2]:
import scipy.stats

In [112]:
arr_clipa = 0
arr_clipb = 120
sd = 1000
vloc = 40

scipy.stats.truncnorm.rvs((arr_clipa - vloc)/sd, (arr_clipb - vloc)/sd, loc = 40, scale = sd, size = 100)

array([111.13893724,  35.89918243, 115.81964782,  20.8859525 ,
        28.31727721,  94.57664582,  39.66243067,  13.41020977,
        39.01117702,  92.13388814,  41.80358177,  33.39092297,
        59.99475713,  94.85129076,  63.6414993 ,  95.58777283,
        32.00342784,  98.78513489,  56.08158286, 109.24966333,
        24.1177839 ,   1.3835081 ,  23.24742918,  53.21201742,
       119.63922036, 108.72019315, 111.42170692,  24.65257178,
        94.95741322,  32.78101791, 104.09199581,  31.73486585,
        22.81574144,  45.7727699 ,  56.44219393,  91.60181372,
        89.77552699,  31.16994997,  28.47475784, 107.198945  ,
       107.70795401, 103.10639574,  45.01377463,  70.28065556,
        69.7039475 ,  13.40963872,  23.27969881,  20.59324097,
        86.5933693 ,  73.4080294 ,  91.30896835,  27.89725964,
        24.99636158,  19.18354709, 108.8367    ,  10.26709417,
        10.38388404,  27.27752812,  11.97114006, 106.86198142,
        91.82181905,  73.18991126,  65.04151717,  47.08

In [113]:
import numpy as np

In [118]:
size, array_length = 100, 120
Varray, Aarray = np.zeros((size, array_length)), np.zeros((size, array_length))
Varray

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [125]:
vloc, aloc = 20, 20
array_length = 120
vvar = 1
avar = 1

from scipy.stats import truncnorm

lowerbound, upperbound = ((0 - vloc) / vvar), ((array_length - vloc) / vvar)

# Sample from these stimulus distributions
Vsamples, Asamples = np.round(truncnorm.rvs(lowerbound, upperbound, loc = vloc, scale = vvar, size = size)), np.round(truncnorm.rvs(lowerbound, upperbound, loc = aloc, scale = avar, size = size))

In [132]:
stimarray = np.zeros((size, 2, array_length))
print(stimarray)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
