In [4]:
import numpy as np
import numpy.matlib as ml
import numba
import matplotlib.pyplot as plt

In [6]:
from test import simulate_data

In [7]:
N = 10000
pCommon, sigV, sigA, sigP = 0.27, 1, 1, 10
varV, varA, varP = sigV**2, sigA**2, sigP**2
vloc, aloc = 24, 24

In [8]:
from bcimodel import get_conditions, bciobjective

In [9]:
possible_locations = np.array([-24,-12,0,12,24])
variance_conditions = [8]
conditions = get_conditions(possible_locations, variance_conditions)
data = simulate_data(possible_locations, variance_conditions)
pars = [pCommon, sigV, sigA, sigP, data, conditions, possible_locations, 100]
bciobjective(pars)

[array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.01]), array([0.

array([-inf, -inf])

In [10]:
data

{(-24, -24, 8): [[8846, 1153, 1, 0, 0], [7759, 2096, 143, 2, 0]],
 (-24, -12, 8): [[8849, 1149, 2, 0, 0], [2224, 5544, 2108, 124, 0]],
 (-24, 0, 8): [[8804, 1195, 1, 0, 0], [140, 2100, 5490, 2134, 136]],
 (-24, 12, 8): [[8826, 1172, 2, 0, 0], [0, 111, 2177, 5380, 2332]],
 (-24, 24, 8): [[8838, 1162, 0, 0, 0], [0, 1, 135, 2103, 7761]],
 (-12, -24, 8): [[1246, 7587, 1165, 2, 0], [7737, 2130, 131, 2, 0]],
 (-12, -12, 8): [[1196, 7696, 1107, 1, 0], [2263, 5522, 2096, 118, 1]],
 (-12, 0, 8): [[1134, 7743, 1123, 0, 0], [119, 2102, 5489, 2187, 103]],
 (-12, 12, 8): [[1096, 7754, 1150, 0, 0], [0, 104, 2136, 5443, 2317]],
 (-12, 24, 8): [[1085, 7772, 1142, 1, 0], [0, 1, 120, 2147, 7732]],
 (0, -24, 8): [[2, 1199, 7641, 1157, 1], [7801, 2090, 108, 1, 0]],
 (0, -12, 8): [[0, 1181, 7702, 1117, 0], [2384, 5367, 2134, 115, 0]],
 (0, 0, 8): [[1, 1237, 7603, 1157, 2], [113, 2166, 5432, 2176, 113]],
 (0, 12, 8): [[0, 1170, 7663, 1165, 2], [0, 137, 2092, 5472, 2299]],
 (0, 24, 8): [[1, 1143, 7704, 1149,

In [13]:
import numpy as np
def clip(arr, roundup = 0.001): # numpyify this function
    
    def clipper(x):
        for i in range(len(x)):
            if x[i] == 0:
                x[i] += roundup
                print(x[i])
            return x
        
    return np.apply_along_axis(clipper, 0, arr)

In [14]:
arr = clip(np.array([0, 0, 0, 23, 42, 51]))
print(arr)

0
[ 0  0  0 23 42 51]


In [113]:
def clip(arr, roundup = 0.001):
    arr = np.clip(arr, 0.001, np.inf)
    return arr

In [68]:
del arr

In [115]:
arr7 = np.array([0, 0, 0, 44, 55])
arr2 = clip(arr7)
arr2[3]

44.0

In [85]:
type(arr2)

NoneType

In [82]:
arr2

In [58]:
arr

array([ 0,  0,  0, 23, 42, 51])

In [124]:
x = np.array([5,5,5,5,6,6,6,6,66])
unique, counts = np.unique(x, return_counts = True)


(array([ 5,  6, 66]), array([4, 4, 1]))

In [129]:
def counter(arr, possible_locations):
    init_counts = np.zeros([5,])
    poss_arr = np.stack((possible_locations, init_counts), axis = 0)
    counts = np.asarray(np.unique(arr, return_counts = True))
    indices = np.where(np.in1d(poss_locs, counts))[0]
    # so we have the indices of the values we want in the counts array

    return counts

def counter2(binned, possible_locations): # base this on numpy too
    return [binned.count(bvc) for bvc in possible_locations]

counter(x)

array([4, 4, 1])

In [172]:
arr = np.array([4,4,4,4,4,4,4])
poss_locs, init_counts = np.array([1,2,3,4,5]), np.zeros([5,])
poss_arr = np.stack((poss_locs, init_counts), axis = 0)
counts = np.asarray(np.unique(arr, return_counts = True))
indices = np.where(np.in1d(poss_locs, counts))[0]
print(poss_arr)
print(counts)
print(indices)
# so then at index three of poss_arr[1]
# change to count value 

[[1. 2. 3. 4. 5.]
 [0. 0. 0. 0. 0.]]
[[4]
 [7]]
[3]


In [177]:
arr = np.array([1,2,3,4,5])
poss = np.array([1,2,3,4,5])
counter(arr, poss)

array([1, 1, 1, 1, 1])

In [178]:
%timeit counter(arr, poss)

3.24 µs ± 75.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
