In [1]:
from generatestimuli import stimGenerator
import numpy as np
from scipy.stats import truncnorm

In [2]:
lowerbound, upperbound, vloc, vvar, size = 0, 100, 20, 2, 1000
truncnorm.rvs(lowerbound, upperbound, loc = vloc, scale = vvar, size = size)

array([20.61131903, 22.67856639, 24.38245115, 20.89936172, 20.79855933,
       22.61368054, 23.07900461, 20.04667323, 20.43567874, 21.39380792,
       21.28091162, 22.42462249, 22.53853891, 21.33919716, 20.01024037,
       20.06852073, 22.31311422, 21.57873452, 20.42714833, 22.41106785,
       22.23589454, 21.17487174, 20.99733554, 21.46992257, 21.87978123,
       20.85878101, 20.08177685, 24.79848384, 21.61024986, 21.4876191 ,
       20.9870978 , 20.80540123, 20.68713008, 22.98796367, 21.02180713,
       21.8859298 , 22.99819883, 22.947391  , 20.96519554, 22.31728473,
       24.2594207 , 20.17339175, 20.40169596, 21.38183731, 21.07152072,
       24.08478891, 20.24376635, 22.75368936, 20.83716401, 22.47004831,
       21.0699217 , 23.0266712 , 22.6901951 , 20.45492149, 22.07285244,
       21.47060415, 23.29869962, 23.65389154, 21.35515055, 20.56180568,
       21.72351904, 21.64375868, 21.21065505, 20.07969539, 20.37082309,
       20.67136586, 22.10386563, 20.52001482, 20.10695131, 20.62

In [1]:
from generatestimuli import stimGenerator

In [2]:
getnstim = stimGenerator(int(120), 2, 3, [1,2])
getnstim.generate(1000, "test", fext = '')

Loaded stimulus generator.
i 40 j 40 c 0 p 37 q 37 vspread [38, 40, 42] aspread [38, 40, 42]
i 40 j 40 c 0 p 38 q 38 vspread [38, 40, 42] aspread [38, 40, 42]
i 40 j 40 c 0 p 39 q 39 vspread [38, 40, 42] aspread [38, 40, 42]
i 40 j 40 c 0 p 40 q 40 vspread [38, 40, 42] aspread [38, 40, 42]
i 42 j 40 c 1 p 39 q 37 vspread [40, 42, 44] aspread [38, 40, 42]
i 42 j 40 c 1 p 40 q 38 vspread [40, 42, 44] aspread [38, 40, 42]
i 42 j 40 c 1 p 41 q 39 vspread [40, 42, 44] aspread [38, 40, 42]
i 42 j 40 c 1 p 42 q 40 vspread [40, 42, 44] aspread [38, 40, 42]
i 39 j 39 c 2 p 36 q 36 vspread [37, 39, 41] aspread [37, 39, 41]
i 39 j 39 c 2 p 37 q 37 vspread [37, 39, 41] aspread [37, 39, 41]
i 39 j 39 c 2 p 38 q 38 vspread [37, 39, 41] aspread [37, 39, 41]
i 39 j 39 c 2 p 39 q 39 vspread [37, 39, 41] aspread [37, 39, 41]
i 39 j 42 c 3 p 36 q 39 vspread [37, 39, 41] aspread [40, 42, 44]
i 39 j 42 c 3 p 37 q 40 vspread [37, 39, 41] aspread [40, 42, 44]
i 39 j 42 c 3 p 38 q 41 vspread [37, 39, 41] aspr

IndexError: index 120 is out of bounds for axis 0 with size 120

In [23]:
from generatestimuli import trialgen
trialgen(120, 3, 100, 20, 20, 1, 8)[0]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.,

In [25]:
arr = np.zeros([10000, 2, 120])

In [27]:
import tensorflow as tf

tf.convert_to_tensor(arr)

<tf.Tensor: shape=(10000, 2, 120), dtype=float64, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])>